apiVersion: v1 
kind: Pod 
metadata:
  name: pod1
  namespace: test
  labels:
    app: java 
spec:
  containers:
  - name: sample
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8080
    resources:
      requests: 
        cpu: 200m
        memory: 256Mi
      limits: 
        cpu: 500m
        memory:  600Mi  

