apiVersion: v1 
kind: Namespace
metadata:
  name: testing
  labels:
    team: test 

---

apiVersion: v1 
kind: ResourceQuota
metadata:
  name: testrq
  namespace: testing
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: 2 
