apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxnginx-ds
spec:
  selector:

    matchLabels:
      app: nginx-pod

  template:

    metadata:

      name: nginx-pod

      labels:
        app: nginx-pod

    spec:
      containers:
      - name: webserver
        image: prometheus
        ports:
        - containerPort: 80